### ISSUE TITLE
Possible improvement for add command

### ISSUE THREAD

**Issue by ZhongXiangWong** [AY2223S2-CS2113-W13-3/tp#100]
Make it such that units cannot be added if quantity does not exist, but at the same time can have quantity without units.

_Example_:
**Possible**
<code>add -n egg -e 12/12/2023 -q 10</code> 
<code>add -n milk -e 12/12/2023 -q 1 -u packet</code>
**Impossible**
<code>add -n milk -e 12/12/2023 -u packet</code>

**Comment by tsx0314** [comment]
okk will update this part later!
