### ISSUE TITLE
[PE-D][Tester A] update feature does not handle double as an index

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W13-3/tp#115]
![image.png](https://raw.githubusercontent.com/Samueltansw/ped/master/files/f84fe543-9856-42f8-9a0c-419a8ffe79ac.png)

As shown in the image, when I enter "update 3.0", the program crashes with NumberFormatException thrown. 

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Samueltansw/ped#5

**Comment by DavidVin357** [comment]
Resolved here (validation should allow only integers):
https://github.com/AY2223S2-CS2113-W13-3/tp/pull/173
