### ISSUE TITLE
[PE-D][Tester D] Legitimate unit of measurement that is more than 1 word long cannot be used

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W13-3/tp#128]
Upon entering a valid unit of measurement that is more than 1 word long, the application recognizes it as an invalid input.

<hr>

![image.png](https://raw.githubusercontent.com/sansders/ped/main/files/15a2cd05-8cc4-4396-bc23-f6c067446ef1.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: sansders/ped#5

**Comment by wanjuin** [comment]
can fix the "ADD_COMMAND_PATTERN" part
