### ISSUE TITLE
[PE-D][Tester B] Duke crashes when txt file is modified (unhandled exception)

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W13-3/tp#133]
![image.png](https://raw.githubusercontent.com/kishore-a00/ped/main/files/c083b214-7d05-42a1-835d-c37e93dd2b14.png)

To reproduce this error, edit the text file as follows:

milk « 01/04/2023 « 0.0 « null « UNCLASSIFIED_FOOD
milk « 01/04/2021 « 0.0 « null « OTHERS
fooood « 12/02/2024 « 0.0 «  « « « « « OTHERS
a « 31/12/2023 « 9.0 « g « UNCLASSIFIED_FOOD
a « 31/12/2023 « 9.0 « 9 « UNCLASSIFIED_FOOD

I believe adding additional « crashes the programme. Do include another exception to catch to avoid this.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: kishore-a00/ped#4

**Comment by DavidVin357** [comment]
Invalid food values in file also fixed here:
https://github.com/AY2223S2-CS2113-W13-3/tp/pull/174
